### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by BryanJacobs02** [INFO-526-F24/project-01-MildCats#4]
The following is the peer review of the project proposal by MintMindsForDataViz. The team members that participated in this review are 

- Bryan Jacobs - @BryanJacobs02
- Deepak Lingala - @Deepak-Lingala
- Raja Sekhar Malireddy - @Rajamalireddy
- ...

- Describe the goal of the project.
The goal of the project is to determine if extreme weather conditions have any interesting effect on match outcome, and to determine if there is a quantifiable home team advantage in premier league matches.

- Describe the data used or collected.
1. Premier League Match Data from TidyTuesday and Kaggle data sets combined to cover matches from 2021 to 2023. The data contains the date of the match, the teams that played, and stats such as goals, shots and result.
2. Weather Data from the Visual Crossing Platform. The data contains weather condition data in the time and location of the matches in question.
3. Betting Odds Data from Football Data UK. The data contains team names, and betting statistics such as win odds, loss odds, and draw odds.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The exact methods to answer each question are unclear.
To answer the question regarding weather conditions, the team plans to compare match results between the same team over varying weather conditions.
To answer the question regarding home team advantage they will analyze the data to determine if there is a significant increase in teams' performances at home compared to when they are away.

- Is there anything that is unclear from the proposal?
While the general direction for each question is clear, the exact visualization or approach to be taken is not stated. This is not much of an issue though as the best visualization for a task will evolve throughout answering a question.

- Provide constructive feedback on how the team might be able to improve their project.
The project looks to be very interesting and the proposal shows a clear direction for it. Something that could be helpful in the presentation would be to provide some background on the Premier League and betting odds as a whole, as not everyone knows how these things work.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We think that the analysis of the effect that weather has on Premier League matches is very interesting and should be focused on. In sports, phenomena like underdog victories are extremely difficult to quantify, so we are very interested to see what you all come up with here.

- Provide constructive feedback on any issues with file and/or code organization.
The layout of the proposal was perfectly readable. The images provided show the group is clearly organized.

- (Optional) Any further comments or feedback?
Looks great! Excited to see the final product.

**Comment by visren** [comment]
Thanks for the feedback!
