### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by jayast29** [INFO-526-F24/project-01-MildCats#5]
The following is the peer review of the project proposal by Vizcats. The team members that participated in this review are 

- Johnson Jeeva John Jeeva - @Johnson-Jeeva
- Likhith Ramesh - @likhithr007
- Sumanth Manohar - @Sumanthm2001

- Describe the goal of the project.

The project aims to investigate two main questions:
1.	Weather's Effect on Match Outcomes: Does extreme weather impact match outcomes in notable ways?
2.	Home Team Advantage: Is there a quantifiable home team advantage in Premier League matches by referee decisions?

- Describe the data used or collected.

The team uses three main datasets:
1.	Premier League Match Data: Sourced from TidyTuesday and Kaggle, covering matches from 2021 to 2023 with details on dates, teams, goals, shots, and results.
2.	Weather Data: Provided by the Visual Crossing Platform, capturing weather conditions for specific match times and locations.
3.	Betting Odds Data: From Football Data UK, includes team names and betting odds (win, loss, draw).

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

The exact methods for analysis are not fully determined, but the team plans to investigate weather's influence by comparing the performance of the same teams under varying weather conditions to identify any notable patterns. They also intend to evaluate home team advantage by analyzing performance differences between home and away games to determine if a significant advantage exists for teams playing on their home field.

- Is there anything that is unclear from the proposal?

The proposal is generally clear in its objectives and data sources; however, the specific analytical techniques and visualizations planned for answering each question are not detailed. Including these would give a better sense of the project's methodology and help anticipate the types of results that might be expected.

- Provide constructive feedback on how the team might be able to improve their project.

The project direction is promising and has a clear focus, but a few enhancements could strengthen it:
1.	Add Context for Broader Audience: Some background on the Premier League and betting odds would help orient those unfamiliar with the league’s structure or the purpose of betting odds in analysis.
2.	Clarify Methods and Visualizations: While flexibility is a strength, it would be helpful to outline tentative visualizations and analyses. Specifying even initial approaches could streamline the process and support more targeted feedback.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

The weather analysis is particularly intriguing! Highlighting how different conditions might affect match outcomes could add a unique dimension, especially since factors like underdog wins are notoriously hard to quantify.

- Provide constructive feedback on any issues with file and/or code organization.

The file and proposal organization are clear and easy to follow. Staying consistent with this structure should keep future analyses and interpretations accessible.

- (Optional) Any further comments or feedback?

Overall, this project has great potential and a unique approach to Premier League analytics. Looking forward to the final findings, especially any unexpected insights into how weather could be influencing match results!

**Comment by visren** [comment]
Thanks for the feedback!
